# theme: jekyll-theme-architect
# GitHub Stars: https://github.com
# icon: logo.png
favicon: "logo.png"
title: HTML5 Website Templates 
description: 1 HTML5 Website Templates 
GitHub Stars: https://github.com
icon: logo.png
favicon: "logo.png"
show_downloads: true
theme: jekyll-theme-midnight
